# Generated by Django 6.0.7 on 2026-08-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
        ('common', '0001_initial'),
        ('company_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('min_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_backlogs', models.PositiveSmallIntegerField(default=0)),
                ('eligible_passing_year', models.PositiveIntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.officerprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_portal.companyprofile')),
                ('eligible_departments', models.ManyToManyField(to='common.department')),
                ('required_skills', models.ManyToManyField(blank=True, to='common.skill')),
            ],
        ),
    ]
